CREATE TABLE SYS.SYSTABLE (
  creator integer,
  table_type char(13),
  table_name char(128)
);
CREATE TABLE SYS.SYSUSERPERM (
  user_id integer,
  user_name char(128)
);

CREATE TABLE DC.DC_TABLE_A (

);
CREATE TABLE DC.DC_TABLE_B (

);
CREATE TABLE DC.DC_TABLE_C (

);

CREATE TABLE DWHPARTITION (STORAGEID VARCHAR(255), TABLENAME VARCHAR(255), STARTTIME DATETIME, ENDTIME DATETIME, STATUS VARCHAR(10), LOADORDER INTEGER);

