insert into TPActivation (TECHPACK_NAME, STATUS, VERSIONID, TYPE, MODIFIED) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST:((1))', 'ENIQ_EVENT', 0);

insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_IMSI_RANK', '15MIN', -1, 'Measurement', 'sgehextrasmall_15min');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_IMSI_RANK', 'DAY', -1, 'Measurement', 'sgehextrasmall_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_SUC', 'RAW', -1, 'Measurement', 'sgehsmall_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_APN_ERR', '15MIN', -1, 'Measurement', 'sgehextrasmall_15min');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_APN_ERR', 'DAY', -1, 'Measurement', 'sgehextrasmall_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_ERR', 'RAW', -1, 'Measurement', 'sgehsmall_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_APN_SUC', '15MIN', -1, 'Measurement', 'sgehextrasmall_15min');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_APN_SUC', 'DAY', -1, 'Measurement', 'sgehextrasmall_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_SUC_DUBCHECK', 'PLAIN', -1, 'Reference', null);
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('EVENT_E_TEST', 'ACTIVE', 'EVENT_E_TEST_ERR_DUBCHECK', 'PLAIN', -1, 'Reference', null);



insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('sgehextrasmall_15min',	15,	168,	30,	0);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('sgehextrasmall_day',	400,	2160,	1095,	0);
insert into PartitionPlan (PARTITIONPLAN, DEFAULTSTORAGETIME, DEFAULTPARTITIONSIZE, MAXSTORAGETIME, PARTITIONTYPE) values ('sgehsmall_raw',	60000000,	10000000,	120000000,	1);

