insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((802)):DC_E_MGW_ATMPORTBH', 'ATMPORT');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT) values ('DC_E_MGW:((802)):DC_E_MGW_ATMPORT', 'ATMPORT');
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT ) values ('DC_E_CPP:((119)):DC_E_CPP_AAL2AP', 'AAL2AP' );
insert into MEASUREMENTOBJBHSUPPORT (TYPEID, OBJBHSUPPORT ) values ('DC_E_CPP:((119)):DC_E_CPP_AAL2APBH', 'AAL2AP' );
