create view dc.DC_E_MGW_ATMPORTBH_RANKBH as
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_01 union all
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_02 union all
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_03 union all
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_04 union all
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_05 union all
  select * from dc.DC_E_MGW_ATMPORTBH_RANKBH_06;
create view dc.DC_E_MGW_ATMPORT_DAYBH as
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_01 union all
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_02 union all
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_03 union all
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_04 union all
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_05 union all
  select * from dc.DC_E_MGW_ATMPORT_DAYBH_06;
create view dc.DC_E_MGW_ATMPORT_RAW as
  select * from dc.DC_E_MGW_ATMPORT_RAW_01 union all
  select * from dc.DC_E_MGW_ATMPORT_RAW_02 union all
  select * from dc.DC_E_MGW_ATMPORT_RAW_03 union all
  select * from dc.DC_E_MGW_ATMPORT_RAW_04 union all
  select * from dc.DC_E_MGW_ATMPORT_RAW_05 union all
  select * from dc.DC_E_MGW_ATMPORT_RAW_06;
create view dc.DC_E_MGW_ATMPORT_DAY as
  select * from dc.DC_E_MGW_ATMPORT_DAY_01 union all
  select * from dc.DC_E_MGW_ATMPORT_DAY_02 union all
  select * from dc.DC_E_MGW_ATMPORT_DAY_03 union all
  select * from dc.DC_E_MGW_ATMPORT_DAY_04 union all
  select * from dc.DC_E_MGW_ATMPORT_DAY_05 union all
  select * from dc.DC_E_MGW_ATMPORT_DAY_06;
create view dc.DC_E_MGW_ATMPORT_COUNT as
  select * from dc.DC_E_MGW_ATMPORT_COUNT_01 union all
  select * from dc.DC_E_MGW_ATMPORT_COUNT_02 union all
  select * from dc.DC_E_MGW_ATMPORT_COUNT_03 union all
  select * from dc.DC_E_MGW_ATMPORT_COUNT_04 union all
  select * from dc.DC_E_MGW_ATMPORT_COUNT_05 union all
  select * from dc.DC_E_MGW_ATMPORT_COUNT_06;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_Atmport_RxAtmP( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_RxAtmP',cast(cast((sum(ifnull(pmReceivedAtmCells,0,pmReceivedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_RxAtmP',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_Atmport_RxTxAtmP( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_RxTxAtmP',cast(cast((sum(ifnull(pmReceivedAtmCells,0,pmReceivedAtmCells))+sum(ifnull(pmTransmittedAtmCells,0,pmTransmittedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_RxTxAtmP',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_Atmport_TxAtmP( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_TxAtmP',cast(cast((sum(ifnull(pmTransmittedAtmCells,0,pmTransmittedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'AtmPort_TxAtmP',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_ATMPORT_PP1( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE,MINUTE_OFFSET,SLIDING_WINDOW_SIZE,P_THRESHOLD,N_THRESHOLD,LOOKBACK_DAYS) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP1',cast(cast((sum(ifnull(pmReceivedAtmCells,0,pmReceivedAtmCells))+sum(ifnull(pmTransmittedAtmCells,0,pmTransmittedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE,0,60,0,0,0 from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP1',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_ATMPORT_PP0( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE,MINUTE_OFFSET,SLIDING_WINDOW_SIZE,P_THRESHOLD,N_THRESHOLD,LOOKBACK_DAYS) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP0',cast(cast((sum(ifnull(pmReceivedAtmCells,0,pmReceivedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE,0,60,0,0,0 from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP0',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dc.DC_E_MGW_ATMPORTBH_RANKBH_ATMPORT_PP2( ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DATE_ID,HOUR_ID,ROWSTATUS,BHTYPE,BHVALUE,PERIOD_DURATION,DC_RELEASE,DC_SOURCE,DC_TIMEZONE,MINUTE_OFFSET,SLIDING_WINDOW_SIZE,P_THRESHOLD,N_THRESHOLD,LOOKBACK_DAYS) as select ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP2',cast(cast((sum(ifnull(pmTransmittedAtmCells,0,pmTransmittedAtmCells))) as numeric(18,8)) as numeric(18,8)),sum(DC_E_MGW_ATMPORT_COUNT.PERIOD_DURATION),DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE,0,60,0,0,0 from dc.DC_E_MGW_ATMPORT_COUNT where ROWSTATUS not in( 'SUSPECTED') group by ATMPORT,MGW,OSS_ID,TRANSPORTNETWORK,DC_E_MGW_ATMPORT_COUNT.DATE_ID,DC_E_MGW_ATMPORT_COUNT.HOUR_ID,DC_E_MGW_ATMPORT_COUNT.ROWSTATUS,'ATMPORT_PP2',DC_E_MGW_ATMPORT_COUNT.DC_RELEASE,DC_E_MGW_ATMPORT_COUNT.DC_SOURCE,DC_E_MGW_ATMPORT_COUNT.DC_TIMEZONE;
create view dcpublic.DC_E_MGW_ATMPORTBH_RANKBH
  as select OSS_ID,
    MGW,
    TransportNetwork,
    AtmPort,
    DATACOVERAGE,
    PERIOD_DURATION,
    ROWSTATUS,
    DC_RELEASE,
    DC_SOURCE,
    DC_TIMEZONE,
    DC_SUSPECTFLAG from
    dc.DC_E_MGW_ATMPORTBH_RANKBH where
    ROWSTATUS <> 'DUPLICATE' and ROWSTATUS <> 'SUSPECTED';
create view dcpublic.DC_E_MGW_ATMPORT_DAY
  as select OSS_ID,
    SN,
    NEUN,
    NEDN,
    NESW,
    MGW,
    MOID,
    TransportNetwork,
    AtmPort,
    userLabel,
    DATE_ID,
    DATACOVERAGE,
    PERIOD_DURATION,
    ROWSTATUS,
    DC_RELEASE,
    DC_SOURCE,
    DC_TIMEZONE,
    DC_SUSPECTFLAG,
    pmTransmittedAtmCells,
    pmReceivedAtmCells,
    pmSecondsWithUnexp from
    dc.DC_E_MGW_ATMPORT_DAY where
    ROWSTATUS <> 'DUPLICATE' and ROWSTATUS <> 'SUSPECTED';
create view dcpublic.DC_E_MGW_ATMPORT_DAYBH
  as select OSS_ID,
    SN,
    NEUN,
    NEDN,
    NESW,
    MGW,
    MOID,
    TransportNetwork,
    AtmPort,
    userLabel,
    DATE_ID,
    MIN_ID,
    BHTYPE,
    BUSYHOUR,
    BHCLASS,
    PERIOD_DURATION,
    ROWSTATUS,
    DC_RELEASE,
    DC_SOURCE,
    DC_TIMEZONE,
    DC_SUSPECTFLAG,
    pmTransmittedAtmCells,
    pmReceivedAtmCells,
    pmSecondsWithUnexp from
    dc.DC_E_MGW_ATMPORT_DAYBH where
    ROWSTATUS <> 'DUPLICATE' and ROWSTATUS <> 'SUSPECTED';
create view dcpublic.DC_E_MGW_ATMPORT_RAW
  as select OSS_ID,
    SN,
    NEUN,
    NEDN,
    NESW,
    MGW,
    MOID,
    TransportNetwork,
    AtmPort,
    userLabel,
    DATETIME_ID,
    PERIOD_DURATION,
    ROWSTATUS,
    DC_RELEASE,
    DC_SOURCE,
    DC_TIMEZONE,
    DC_SUSPECTFLAG,
    UTC_DATETIME_ID,
    pmTransmittedAtmCells,
    pmReceivedAtmCells,
    pmSecondsWithUnexp from
    dc.DC_E_MGW_ATMPORT_RAW where
    ROWSTATUS <> 'DUPLICATE' and ROWSTATUS <> 'SUSPECTED';
create view dcpublic.DC_E_MGW_ATMPORT_COUNT
  as select OSS_ID,
    SN,
    NEUN,
    NEDN,
    NESW,
    MGW,
    MOID,
    TransportNetwork,
    AtmPort,
    userLabel,
    DATETIME_ID,
    PERIOD_DURATION,
    ROWSTATUS,
    DC_RELEASE,
    DC_SOURCE,
    DC_TIMEZONE,
    DC_SUSPECTFLAG,
    UTC_DATETIME_ID,
    pmTransmittedAtmCells,
    pmReceivedAtmCells,
    pmSecondsWithUnexp from
    dc.DC_E_MGW_ATMPORT_COUNT where
    ROWSTATUS <> 'DUPLICATE' and ROWSTATUS <> 'SUSPECTED';
