insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('APN', 'EVENT_E_SGEH:((7))', 'APN', 'varchar', '127', '0', '0');
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('IMSI', 'EVENT_E_SGEH:((7))', 'IMSI', 'unsigned bigint', '0', '0', '0');
insert into GROUPTYPES (GROUPTYPE, VERSIONID, DATANAME, DATATYPE, DATASIZE, DATASCALE, NULLABLE) values ('TAC', 'EVENT_E_SGEH:((7))', 'TAC', 'unsigned int', '0', '0', '0');
