CREATE TABLE DWHCOLUMN (
	STORAGEID varchar(255),
	DATANAME varchar(128),
	COLNUMBER numeric(9, 0),
	DATATYPE varchar(50),
	DATASIZE int,
	DATASCALE int,
	UNIQUEVALUE numeric(9, 0),
	NULLABLE int,
	INDEXES varchar(20),
	UNIQUEKEY int,
	STATUS varchar(10),
	INCLUDESQL int
);
CREATE TABLE DWHPARTITION (
	STORAGEID varchar(255),
	TABLENAME varchar(255),
	STARTTIME timestamp,
	ENDTIME timestamp,
	STATUS varchar(10),
	LOADORDER int
);
CREATE TABLE VERSIONING (
	VERSIONID varchar(128),
	DESCRIPTION varchar(50),
	STATUS numeric(9, 0),
	TECHPACK_NAME varchar(30),
	TECHPACK_VERSION varchar(32),
	TECHPACK_TYPE varchar(10),
	PRODUCT_NUMBER varchar(255),
	LOCKEDBY varchar(255),
	LOCKDATE timestamp,
	BASEDEFINITION varchar(128),
	BASEVERSION varchar(16),
	INSTALLDESCRIPTION varchar(32000),
	UNIVERSENAME varchar(30),
	UNIVERSEEXTENSION varchar(16),
	ENIQ_LEVEL varchar(12),
	LICENSENAME varchar(255)
);
CREATE TABLE DWHTECHPACKS (
	TECHPACK_NAME varchar(30),
	VERSIONID varchar(128),
	CREATIONDATE timestamp
);
CREATE TABLE GROUPTYPES (
	GROUPTYPE varchar(64),
	VERSIONID varchar(128),
	DATANAME varchar(128),
	DATATYPE varchar(50),
	DATASIZE int,
	DATASCALE int,
	NULLABLE smallint
);
CREATE TABLE MEASUREMENTTABLE (
	MTABLEID varchar(255),
	TABLELEVEL varchar(50),
	TYPEID varchar(255),
	BASETABLENAME varchar(255),
	DEFAULT_TEMPLATE varchar(50),
	PARTITIONPLAN varchar(128)
);
CREATE TABLE REFERENCETABLE (
	TYPEID varchar(255),
	VERSIONID varchar(128),
	TYPENAME varchar(255),
	OBJECTID varchar(255),
	OBJECTNAME varchar(255),
	OBJECTVERSION varchar(50),
	OBJECTTYPE varchar(255),
	DESCRIPTION varchar(32000),
	STATUS numeric(9, 0),
	UPDATE_POLICY numeric(9, 0),
	TABLE_TYPE varchar(12),
	DATAFORMATSUPPORT int,
	BASEDEF int
);
CREATE TABLE TPACTIVATION (
	TECHPACK_NAME varchar(30),
	STATUS varchar(10),
	VERSIONID varchar(128),
	TYPE varchar(10),
	MODIFIED int
);
CREATE TABLE MEASUREMENTOBJBHSUPPORT (
	TYPEID varchar(255),
	OBJBHSUPPORT varchar(32)
);
CREATE TABLE MEASUREMENTTYPE (
	TYPEID varchar(255),
	TYPECLASSID varchar(255),
	TYPENAME varchar(255),
	VENDORID varchar(128),
	FOLDERNAME varchar(128),
	DESCRIPTION varchar(32000),
	STATUS numeric(9, 0),
	VERSIONID varchar(128),
	OBJECTID varchar(255),
	OBJECTNAME varchar(255),
	OBJECTVERSION int,
	OBJECTTYPE varchar(255),
	JOINABLE varchar(255),
	SIZING varchar(16),
	TOTALAGG int,
	ELEMENTBHSUPPORT int,
	RANKINGTABLE int,
	DELTACALCSUPPORT int,
	PLAINTABLE int,
	UNIVERSEEXTENSION varchar(12),
	VECTORSUPPORT int,
	DATAFORMATSUPPORT int,
	FOLLOWJOHN int,
	ONEMINAGG int,
	FIFTEENMINAGG int,
	EVENTSCALCTABLE int,
	MIXEDPARTITIONSTABLE int,
	LOADFILE_DUP_CHECK int,	SONAGG int,	SONFIFTEENMINAGG int,	ROPGRPCELL varchar(255)
);
CREATE TABLE TYPEACTIVATION (
	TECHPACK_NAME varchar(30),
	STATUS varchar(10),
	TYPENAME varchar(255),
	TABLELEVEL varchar(50),
	STORAGETIME numeric(15, 0),
	TYPE varchar(12),
	PARTITIONPLAN varchar(128)
);
CREATE TABLE DWHTYPE (
	TECHPACK_NAME varchar(30),
	TYPENAME varchar(255),
	TABLELEVEL varchar(50),
	STORAGEID varchar(255),
	PARTITIONSIZE numeric(9, 0),
	PARTITIONCOUNT numeric(9, 0),
	STATUS varchar(50),
	TYPE varchar(50),
	OWNER varchar(50),
	VIEWTEMPLATE varchar(255),
	CREATETEMPLATE varchar(255),
	NEXTPARTITIONTIME timestamp,
	BASETABLENAME varchar(125),
	DATADATECOLUMN varchar(128),
	PUBLICVIEWTEMPLATE varchar(255),
	PARTITIONPLAN varchar(128)
);
CREATE TABLE PARTITIONPLAN (
	PARTITIONPLAN varchar(128),
	DEFAULTSTORAGETIME numeric(20, 0),
	DEFAULTPARTITIONSIZE numeric(20, 0),
	MAXSTORAGETIME numeric(20, 0),
	PARTITIONTYPE tinyint
);
CREATE TABLE META_DATABASES (
	USERNAME varchar(30),
	VERSION_NUMBER varchar(32),
	TYPE_NAME varchar(15),
	CONNECTION_ID numeric(38, 0),
	CONNECTION_NAME varchar(30),
	CONNECTION_STRING varchar(400),
	PASSWORD varchar(30),
	DESCRIPTION varchar(32000),
	DRIVER_NAME varchar(100),
	DB_LINK_NAME varchar(128)
);
