insert into TPACTIVATION (TECHPACK_NAME, STATUS, VERSIONID, TYPE, MODIFIED) values ('EVENT_E_SGEH', 'ACTIVE', 'EVENT_E_SGEH:((7))', 'ENIQ_EVENT', '0');
insert into TPACTIVATION (TECHPACK_NAME, STATUS, VERSIONID, TYPE, MODIFIED) values ('DIM_E_RBS', 'ACTIVE', 'DIM_E_RBS:((42))', 'ENIQ_EVENT', '0');
