CREATE TABLE META_DATABASES (
	USERNAME VARCHAR(30), 
	VERSION_NUMBER VARCHAR(32), 
	TYPE_NAME VARCHAR(15), 
	CONNECTION_ID NUMERIC(38), 
	CONNECTION_NAME VARCHAR(30), 
	CONNECTION_STRING VARCHAR(200), 
	PASSWORD VARCHAR(30), 
	DESCRIPTION VARCHAR(32000), 
	DRIVER_NAME VARCHAR(100), 
	DB_LINK_NAME VARCHAR(128)
);
